# -*- yaml -*-
# non-firstttime installation of the kiss-configure stuff
---
# this is ugly, but how to find it for roles included from role_path?
- name: copy kiss-configure directory
  synchronize: src="{{source_dir}}/node/"
    dest=/srv/kiss-configure/ delete=false

- name: fix permissions on roles
  command: chmod -R ug=rX,o= /srv/kiss-configure
    
- name: git add some files
  command: git add {{item}}
  args:
    chdir: /srv/kiss-configure
  with_items:
    - kiss-configure
    - kiss-configure.yml
    - roles/
    - group_vars/
    - vm-config/
    - ansible-hosts
    - ansible.cfg
    
