- name: install kissclusterd
  copy: src=/data/projects/kisscluster/kissclusterd dest=/usr/sbin/kissclusterd
    owner=root group=root mode=0555
  notify: kissclusterd reload

- name: create kissclusterd group
  group: name=kissclusterd system=yes
  
- name: create kissclusterd user
  user: name=kissclusterd group=kissclusterd
    comment="KISScluster daemon" system=yes

- name: install sudoers file for kissclusterd
  template: src=sudoers.j2 dest=/etc/sudoers.d/kissclusterd
    owner=root group=root mode=0440 validate=visudo -c -f %s

- name: install kissclusterd.conf
  template: src=kissclusterd.conf.j2 dest=/etc/kissclusterd.conf
    owner=root group=kissclusterd mode=0440
  notify: kissclusterd reload

- name: install kissclusterd service file
  template: src=kissclusterd.service.j2
    dest=/etc/systemd/system/kissclusterd.service
    owner=root group=root mode=0444
  notify: systemctl daemon-reload

- name: enable kissclusterd service
  service: name=kissclusterd enabled=yes 
  # do not start; depends on drbd, which needs resources...

