# -*- yaml -*-
# installation/update of the kiss-configure stuff
---
# this is a bit convoluted
# some steps run only on the "primary" node
# some steps run only during first installation, some during updates

# these two should only run once in the lifetime of a cluster
- name: check for kiss-configure repo
  stat: path=/srv/kiss-configure.git
  register: kcg_stat

- name: run firsttime steps
  include: kiss-configure-firsttime.yml
  when: not kcg_stat.stat.exists

- name: run firsttime steps only on primary
  include: kiss-configure-firsttime-primary.yml
  when: not kcg_stat.stat.exists and inventory_hostname == cluster_members[0].name

# the following steps should run at every update
- name: run update steps only on primary
  include: kiss-configure-updates-primary.yml
  when: inventory_hostname == cluster_members[0].name

- name: set permissions on working copy (1)
  command: chown -R root.adm /srv/kiss-configure
  
- name: set permissions on working copy (2)
  command: chmod -R ug+rwX /srv/kiss-configure

- name: set permissions on working copy (3)
  shell: find /srv/kiss-configure -type d -print0 | xargs -0r chmod g+s

- name: install sudoers file for adm group
  template: src=sudoers-adm.j2 dest=/etc/sudoers.d/adm
    owner=root group=root mode=0440 validate="visudo -c -f %s"

- name: make /etc/vm directory
  file: dest=/etc/vm state=directory owner=root group=adm mode=0770
  