# -*- yaml -*-
# installation of the kiss-configure stuff
#
# first time steps to run on primary only
# mostly filling stuff into the working dir
# so afterwards there's one location that can be pushed to the repo
---
- name: install ansible config files
  template: src={{item}}.j2 dest=/srv/kiss-configure/{{item}}
    owner=root group=adm mode=0660
  with_items:
    - ansible.cfg
    - ansible-hosts

- name: mkdir
  file: dest=/srv/kiss-configure/{{item}} state=directory
    owner=root group=adm mode=0775
  with_items:
    - vm-config/{{cluster_name}}
    - group_vars

- name: copy initial group_vars for cluster
  copy: src=group_vars/{{cluster_name}}.yml
    dest=/srv/kiss-configure/group_vars/{{cluster_name}}.yml
    owner=root group=adm mode=0660

    