# -*- yaml -*-
# non-firstttime installation of the kiss-configure stuff
---
- name: install kiss-configure script
  copy: src=kiss-configure dest=/srv/kiss-configure/kiss-configure
    owner=root group=adm mode=0550

- name: install ansible files from templates
  template: src={{item}}.j2 dest=/srv/kiss-configure/{{item}}
    owner=root group=adm mode=0660
  with_items:
    - kiss-configure.yml

#- name: mkdir roles
#  file: dest=/srv/kiss-configure/roles/kisscluster-vms state=directory
#    owner=root group=adm mode=0775
    
# this is ugly, but how to find it for roles included from role_path?
- name: install kisscluster-vms role
  synchronize: src="{{_original_file|regex_replace('/[^/]+/[^/]+/[^/]+$', '/kisscluster-vms')}}"
    dest=/srv/kiss-configure/roles/ delete=true 

- name: fix permissions on roles
  command: chmod -R ug=rX,o= /srv/kiss-configure/roles
    
- name: git add some files
  command: git add {{item}}
  args:
    chdir: /srv/kiss-configure
  with_items:
    - kiss-configure
    - kiss-configure.yml
    - roles/
    - group_vars/
    - vm-config/
    - ansible-hosts
    - ansible.cfg
    