# -*- yaml -*-
---
- name: install packages
  apt: pkg={{item}} state=present install_recommends=no
  with_items:
    - bridge-utils
    - vlan
    - ntp
    - lvm2
    - drbd-utils
    - qemu-kvm
    - socat
    - iproute2
    - fping
    - perl
    - libconfig-tiny-perl
    - libipc-system-simple-perl
    - libdigest-sha-perl
    - libyaml-perl
    - libnet-openssh-perl
    - sudo
    - git
    - rsync
    - ansible

- name: remove some stuff
  apt: pkg={{item}} state=absent purge=yes
  with_items:
    - avahi-autoipd
    - isc-dhcp-client
    - isc-dhcp-common
    - avahi-daemon
    - network-manager

- name: install helpers
  copy: src={{item}} dest=/usr/sbin/{{item}}
    owner=root group=root mode=0555
  with_items:
    - kiss-vm-monitor
    - kiss-overview
    - kiss-nuke-vm
    - kiss-boot-iso
    - kiss-migrate
