# -*- yaml -*-
---
- name: make root ssh key
  command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N '' -q
  args:
    creates: /root/.ssh/id_ed25519

- name: fetch root ssh pubkey
  fetch: src=/root/.ssh/id_ed25519.pub dest=keys/{{inventory_hostname}}_root.pub
    fail_on_missing=yes flat=yes

- name: install root authorized_key
  authorized_key: key="{{ lookup('file', 'keys/' + item.name + '_root.pub') }}"
    user=root state=present   
  with_items: cluster_members
  when: item.name != inventory_hostname
  