# -*- yaml -*-
---
# group disks for access to DRBD devices
- name: create "kvm" user
  user: name=kvm comment="kvm virtualisation user" group=kvm
    groups=disk home=/run/kvm system=yes state=present

- name: install unit files
  template: src={{item}}.j2 dest=/etc/systemd/system/{{item}}
    owner=root group=root mode=0444
  with_items:
    - no-vms.target
    - primary-vms.target
    - all-vms.target
    - vm@.service
    - drbd-resource@.service

- name: install tmpfiles.d for /run/kvm
  template: src=run_kvm_tmpfiles.j2 dest=/etc/tmpfiles.d/run_kvm.conf
    owner=root group=root mode=0444
    
- name: enable unit files
  command: /bin/systemctl enable {{item}}
  with_items:
    - no-vms.target
    - primary-vms.target
    - all-vms.target

- name: install drbd-primary-helper
  template: src=drbd-primary-helper.j2 dest=/sbin/drbd-primary-helper
    owner=root group=root mode=0555

- name: systemctl daemon-reload
  command: /bin/systemctl daemon-reload
  